dist: 'trusty'
language: node_js
os:
- linux
- windows
node_js:
- '6'
- '8'
- '10'
jobs:
  include:
    - name: 'Coverage'
      node_js: stable
      os: linux
      script:
        - npm run test-unit
        - bash <(curl -s https://codecov.io/bash) -c -Z -f .coverage/coverage-final.json -F unit
#before_install:
#- |
#  if [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then
#    openssl aes-256-cbc -K $encrypted_9a2810c1eadf_key -iv $encrypted_9a2810c1eadf_iv -in ./.ci/deploy-key.enc -out ./.ci/deploy-key -d
#  fi;
#
#after_success:
#- |
#  if [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then
#    eval "$(ssh-agent)"
#    echo "Publishing Docs";
#    chmod 600 ./.ci/deploy-key;
#    ssh-add ./.ci/deploy-key;
#    openssl aes-256-cbc -K $encrypted_9a2810c1eadf_key -iv $encrypted_9a2810c1eadf_iv -in ./.ci/deploy-key.enc -out ./.ci/deploy-key -d;
#    npm run publish-docs;
#    ssh-agent -k
#  fi;
notifications:
  slack:
    secure: PuYBCkRXgUKxoFMyTZdYcxplpgW+T/hxq54gsFOcAxN079i7PTD/GmGIgKM1RviCocvroUst5bW3ULk3haYUb8gQSCyAeHzRl00DaoOXshTRjFzJyU6m5wbT/R45dh6ZO2BT6uwlVU95KznieCC+yjlbppPOis8bwxra08ODnsA1L7OeI7fVlKjyh+lPA4qnmuYpNtMfTO5mmHroHBS5nWoB1WctWuZQGSfDYLUr/XrhKkJOBbv7FI7setTroIRF4Rs9nIFEF3mzTuUK5VV6lQAZRzNHKmgD9DmGVeaB5Y4fWEznocV1d6cInsjMr4EyMYziyOFnnPZAk8GZapMDwD0/5E9L5+Q8uXhFhVHYurpZnP+wylqZmnfb4UaFcP96BBaavhfF/ai+LWlLbHiL5b1HX4dlauNfHdq1W1YCILI2Atfr+36rqu3102S6HHkOssoTw09ftLfQHuF6CNYnVE5cS40pupwFZj3o0h9yQnCFDPxlq2ls+hon+PKL9wCHL5MlG+jQZDDL8eZC8F9CoZUyVIxNhoh0fnZ+t4bIlGW5eB8f8oMCxcnjocxZpichfAsmuaPh/e2KfdoF/B7ce6+Tb3/YXqo5QVTsJ1Vzi4I7c3jx1Q0DAyZODsBKyE0y7NfmeVNap0WIgajiJBoKji8Fjw+tDfa3hSb4yyPSG6w=
